### ISSUE TITLE
Prevent lead-acid batteries from deep-discharging

### ISSUE THREAD

**Issue by valeriansaliou** [makers-for-life/makair-firmware#14]
Each battery unit voltage can be monitored via the software. Whenever a certain low threshold voltage is reached, the whole system should shut down in order to prevent damaging the battery (ie. deep-discharging it). However, the respirator _might_ enter into a non-recoverable hardware state.

**Comment by Benhalor** [comment]
si <20V, on coupe tout, et pas de retour arrière possible (couper les timers aussi). Si démarrage avec <22V, refus de fonctionnement
