### ISSUE TITLE
Sauvegarde des réglages dans l'EEPROM

### ISSUE THREAD

**Issue by VincentLECUNFF** [makers-for-life/makair-firmware#23]
Depuis la V2 Hardware, il y a une EEPROM qui permet le stockage des réglages usine, ...

**Comment by dsferruzza** [comment]
Comme c'est une fonctionnalité "lourde" (il faut bien parler avec l'EEPROM, gérer le schémas des données qu'on y met, …) on se voit mal le faire tant que ce n'est pas pour appuyer une fonctionnalité absolument nécessaire et poussée par l'ensemble de l'équipe R&D. Je ferme pour l'instant mais on a bien en tête qu'on a cette mémoire de dispo.

**Comment by baptistejamin** [comment]
Il y a du moins un intéret. Par exemple sauvegarder des réglagles qui permettent de restart la machine dans un état propre suite à un Watchdog
