### ISSUE TITLE
Convert telemetry acknowledge pressures in cmh2O

### ISSUE THREAD

**Issue by Benhalor** [makers-for-life/makair-firmware#40]
When sending telemetry acknowledge messages for pressures, convert it to cmH2O instead of sending it in mmH2O

**Comment by dsferruzza** [comment]
I thought we decided to stay with mmH2O in telemetry to keep accurate measurements and let consumers (UI, database, ...) round it on their side if wanted. Did something changed that makes it necessary to reevaluate this position?

**Comment by Benhalor** [comment]
My bad, you are right David, all the value should be sent in mmH2O for accurracy, and displayed in cmH20
But there is still an inconsistency because value are sent in cmH2O in sendMachineStateSnapshot(...), but in mmH2O in sendControlAck(...)
