### ISSUE TITLE
When calibration failed, restart calibration if START is pressed

### ISSUE THREAD

**Issue by baptistejamin** [makers-for-life/makair-firmware#65]
Currently, when calibration test fails, the only way is to completely switch off the machine and then start again.

it would be great to do a new calibration if START is pressed, without restarting the machine

**Comment by valeriansaliou** [comment]
+ adding to that, entities could be added to the telemetry / control protocols to get calibration information / restart a calibration. Could be added in the advanced settings modal in the UI.
